################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
      - node-backend-net
      - alfresco-net
      - import-net
    volumes:
      - ./data:/data

volumes:
  data:

networks:
  node-red-net:
  node-backend-net:
    name: backend_net
    external: true
  alfresco-net:
    name: alfresco_backend
    external: true
  import-net:
    name: import-backend
    external: true
